language: go
go: '1.24'

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure -v
  - go get -v golang.org/x/lint/golint
  - go get -v golang.org/x/tools/cmd/goimports

script:
  - make ci
